"""Route bounded notebook model work through Codex CLI profiles.

The router never writes the question database. It selects a model, runs Codex
in a read-only sandbox, validates the structured envelope, and writes only the
payload plus a metadata-only routing audit record.
"""

from __future__ import annotations

import argparse
from datetime import datetime
import importlib.util
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ROUTING_CONFIG = PROJECT_ROOT / "config" / "codex-model-routing.json"
NOTEBOOK = (
    PROJECT_ROOT
    / ".agents"
    / "skills"
    / "math-error-notebook"
    / "scripts"
    / "notebook.py"
)


class RoutingBlocked(RuntimeError):
    """The strongest configured route still lacks enough evidence."""


def read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(payload, dict):
        raise ValueError(f"JSON object required: {path}")
    return payload


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    temporary.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def load_routing_config(path: Path = ROUTING_CONFIG) -> dict[str, Any]:
    config = read_json(path)
    if config.get("schema") != "math-codex-model-routing/v1":
        raise ValueError("unsupported Codex routing config schema")
    if not config.get("profiles") or not config.get("tasks"):
        raise ValueError("routing config requires profiles and tasks")
    return config


def select_route(
    config: dict[str, Any],
    task: str,
    risks: list[str] | None = None,
    has_images: bool = False,
    force_profile: str | None = None,
) -> dict[str, Any]:
    tasks = config["tasks"]
    profiles = config["profiles"]
    if task not in tasks:
        raise ValueError(f"unknown task: {task}")
    task_config = tasks[task]
    profile_key = str(task_config["profile"])
    if force_profile:
        if force_profile not in profiles:
            raise ValueError(f"unknown profile: {force_profile}")
        profile_key = force_profile
    else:
        requested = list(risks or [])
        unknown = sorted(set(requested) - set(config.get("risks") or {}))
        if unknown:
            raise ValueError("unknown risk flags: " + ", ".join(unknown))
        targets = [config["risks"][risk] for risk in requested]
        if has_images and profiles[profile_key]["rank"] < profiles["standard"]["rank"]:
            targets.append("standard")
        for target in targets:
            if profiles[target]["rank"] > profiles[profile_key]["rank"]:
                profile_key = target

    profile = profiles[profile_key]
    base_profile = str(task_config["profile"])
    effort = (
        task_config.get("reasoning_effort")
        if profile_key == base_profile
        else None
    ) or profile["reasoning_effort"]
    schema_path = (PROJECT_ROOT / str(task_config["schema"])).resolve()
    if not schema_path.is_file():
        raise ValueError(f"missing output schema: {schema_path}")
    return {
        "task": task,
        "profile_key": profile_key,
        "codex_profile": profile["codex_profile"],
        "model": profile["model"],
        "reasoning_effort": effort,
        "verbosity": profile["verbosity"],
        "minimum_confidence": float(task_config["minimum_confidence"]),
        "context_task": task_config["context_task"],
        "schema_path": str(schema_path),
        "instruction": task_config["instruction"],
    }


def profile_text(profile: dict[str, Any]) -> str:
    return (
        "# Generated by 李兆霖数学错题本 codex_task_router.py\n"
        f'model = "{profile["model"]}"\n'
        f'model_reasoning_effort = "{profile["reasoning_effort"]}"\n'
        f'model_verbosity = "{profile["verbosity"]}"\n'
    )


def install_profiles(
    config: dict[str, Any], codex_home: Path, force: bool = False
) -> dict[str, Any]:
    codex_home.mkdir(parents=True, exist_ok=True)
    created: list[str] = []
    unchanged: list[str] = []
    for profile in config["profiles"].values():
        target = codex_home / f'{profile["codex_profile"]}.config.toml'
        expected = profile_text(profile)
        if target.exists():
            current = target.read_text(encoding="utf-8-sig")
            if current == expected:
                unchanged.append(target.name)
                continue
            if not force:
                raise ValueError(
                    f"profile already exists with different content: {target}; "
                    "use --force only after reviewing it"
                )
        target.write_text(expected, encoding="utf-8")
        created.append(target.name)
    return {
        "status": "ok",
        "codex_home": str(codex_home.resolve()),
        "created": created,
        "unchanged": unchanged,
    }


def resolve_project_file(value: str | Path, must_exist: bool = True) -> Path:
    path = Path(value)
    if not path.is_absolute():
        path = PROJECT_ROOT / path
    path = path.resolve()
    try:
        path.relative_to(PROJECT_ROOT)
    except ValueError as exc:
        raise ValueError(f"path must stay inside the notebook project: {path}") from exc
    if must_exist and not path.is_file():
        raise ValueError(f"file not found: {path}")
    return path


def run_preflight(context_task: str) -> None:
    commands = [
        [sys.executable, "-X", "utf8", "-B", str(NOTEBOOK), "doctor", "--json"],
        [
            sys.executable,
            "-X",
            "utf8",
            "-B",
            str(NOTEBOOK),
            "agent-context",
            "--task",
            context_task,
            "--json",
        ],
    ]
    for index, command in enumerate(commands):
        result = subprocess.run(
            command,
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        if result.returncode:
            raise RuntimeError(result.stderr.strip() or result.stdout.strip())
        if index == 0 and json.loads(result.stdout).get("status") != "ok":
            raise RuntimeError("notebook doctor did not return status=ok")


def compact_input(path: Path) -> str:
    text = path.read_text(encoding="utf-8-sig")
    if len(text) > 1_000_000:
        raise ValueError("input exceeds 1,000,000 characters; split the task")
    try:
        payload = json.loads(text)
    except json.JSONDecodeError:
        return text.strip()
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":"))


def local_catalogs() -> dict[str, Any]:
    scripts_dir = str(NOTEBOOK.parent)
    if scripts_dir not in sys.path:
        sys.path.insert(0, scripts_dir)
    spec = importlib.util.spec_from_file_location("math_notebook_router_catalog", NOTEBOOK)
    if not spec or not spec.loader:
        raise RuntimeError("cannot load notebook catalogs")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    knowledge_path = (
        PROJECT_ROOT
        / ".agents"
        / "skills"
        / "math-error-notebook"
        / "assets"
        / "knowledge-points.json"
    )
    knowledge = json.loads(knowledge_path.read_text(encoding="utf-8-sig"))
    if not isinstance(knowledge, list):
        raise ValueError("knowledge-points.json must contain an array")
    return {
        "knowledge_codes": [
            {"code": item["code"], "name": item["name"], "grade": item["grade"]}
            for item in knowledge
        ],
        "cause_codes": [
            {"code": code, "name": name}
            for code, name in module.CAUSE_CODES.items()
        ],
        "feature_codes": [
            {"code": code, "name": name}
            for code, name in module.FEATURE_CODES.items()
        ],
    }


def build_prompt(
    route: dict[str, Any],
    input_text: str | None,
    prompt: str | None,
    image_count: int,
) -> str:
    parts = [
        "执行李兆霖数学错题本的一个有边界、只读的模型任务。",
        "本地 doctor 和 agent-context 预检已完成，不要重复运行。",
        "不得修改文件或数据库；只根据可见证据判断，不得补造缺失条件。",
        "最终只返回 output schema 要求的一个 JSON 对象，不要 Markdown 代码围栏。",
        "若证据不足、结果冲突或无法可靠完成，status 必须为 needs_escalation 或 unclear，并写明 escalation_reasons。",
        f"任务：{route['task']}。{route['instruction']}",
    ]
    if input_text:
        parts.append("输入数据：" + input_text)
    if route["task"] == "tag":
        parts.append(
            "可用代码表："
            + json.dumps(local_catalogs(), ensure_ascii=False, separators=(",", ":"))
        )
    if image_count:
        parts.append(f"本次附带 {image_count} 张图片，必须逐张查看后再判断。")
    if prompt:
        parts.append("补充要求：" + prompt.strip())
    return "\n".join(parts)


def codex_binary(requested: str | None = None) -> str:
    found = shutil.which(requested or "codex")
    if not found:
        raise RuntimeError("codex CLI was not found on PATH")
    return found


def run_codex_once(
    route: dict[str, Any],
    prompt: str,
    images: list[Path],
    timeout: int,
    requested_binary: str | None,
) -> tuple[dict[str, Any], float]:
    executable = codex_binary(requested_binary)
    with tempfile.TemporaryDirectory(prefix="math-codex-route-") as temp_dir:
        result_path = Path(temp_dir) / "result.json"
        command = [
            executable,
            "exec",
            "-p",
            route["codex_profile"],
            "-c",
            f'model_reasoning_effort="{route["reasoning_effort"]}"',
            "--ephemeral",
            "-s",
            "read-only",
            "-C",
            str(PROJECT_ROOT),
            "--output-schema",
            route["schema_path"],
            "-o",
            str(result_path),
        ]
        for image in images:
            command.extend(["-i", str(image)])
        command.append("-")
        started = time.monotonic()
        result = subprocess.run(
            command,
            cwd=PROJECT_ROOT,
            input=prompt,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=timeout,
            check=False,
        )
        elapsed = round(time.monotonic() - started, 3)
        if result.returncode:
            detail = (result.stderr or result.stdout).strip()[-2000:]
            raise RuntimeError(
                f"codex exec failed with exit code {result.returncode}: {detail}"
            )
        if not result_path.is_file():
            raise RuntimeError("codex exec did not write its final structured response")
        return read_json(result_path), elapsed


def validate_envelope(result: dict[str, Any]) -> None:
    status = result.get("status")
    if status not in {"complete", "needs_escalation", "unclear"}:
        raise ValueError("model result has invalid status")
    try:
        confidence = float(result.get("confidence"))
    except (TypeError, ValueError) as exc:
        raise ValueError("model result requires numeric confidence") from exc
    if not 0 <= confidence <= 1:
        raise ValueError("model result confidence must be between 0 and 1")
    if not isinstance(result.get("escalation_reasons"), list):
        raise ValueError("model result escalation_reasons must be an array")
    if not isinstance(result.get("payload"), dict):
        raise ValueError("model result payload must be an object")


def effective_confidence(result: dict[str, Any]) -> float:
    values = [float(result["confidence"])]
    items = result.get("payload", {}).get("items")
    if isinstance(items, list):
        for item in items:
            if isinstance(item, dict):
                value = item.get("confidence", item.get("model_confidence"))
                if value is not None:
                    values.append(float(value))
    return min(values)


def validate_payload(task: str, payload: dict[str, Any]) -> None:
    if task in {"grade-text", "grade-photo", "review"}:
        verdict = payload.get("verdict")
        analysis = payload.get("error_analysis")
        if verdict in {"wrong", "partial"} and not isinstance(analysis, dict):
            raise ValueError("wrong or partial grading requires error_analysis")
        if verdict in {"correct", "unclear"} and analysis is not None:
            raise ValueError("correct or unclear grading must not create an error record")
    if task == "generate" and payload.get("verification_status") != "unverified":
        raise ValueError("generated questions must remain unverified")


def audit_route(metadata: dict[str, Any]) -> Path:
    directory = PROJECT_ROOT / "data" / "audits" / "codex-cli-routing"
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S-%f")
    path = directory / f"{stamp}-{uuid.uuid4().hex[:8]}.json"
    write_json(path, metadata)
    return path


def run_task(args: argparse.Namespace, config: dict[str, Any]) -> dict[str, Any]:
    input_path = resolve_project_file(args.input) if args.input else None
    prompt_file = resolve_project_file(args.prompt_file) if args.prompt_file else None
    output_path = resolve_project_file(args.out, must_exist=False)
    images = [resolve_project_file(value) for value in args.image]
    prompt_extra = args.prompt or ""
    if prompt_file:
        prompt_extra = "\n".join(
            item for item in [prompt_extra, prompt_file.read_text(encoding="utf-8-sig")]
            if item
        )
    if not input_path and not prompt_extra.strip():
        raise ValueError("run requires --input, --prompt, or --prompt-file")

    route = select_route(
        config,
        args.task,
        args.risk,
        has_images=bool(images),
        force_profile=args.force_profile,
    )
    if not args.skip_preflight:
        run_preflight(route["context_task"])
    input_text = compact_input(input_path) if input_path else None
    prompt = build_prompt(route, input_text, prompt_extra, len(images))
    attempts: list[dict[str, Any]] = []
    current = route
    while True:
        result, elapsed = run_codex_once(
            current, prompt, images, args.timeout, args.codex_bin
        )
        validate_envelope(result)
        confidence = effective_confidence(result)
        attempts.append({
            "profile": current["profile_key"],
            "model": current["model"],
            "reasoning_effort": current["reasoning_effort"],
            "elapsed_seconds": elapsed,
            "status": result["status"],
            "confidence": confidence,
        })
        needs_more = (
            result["status"] != "complete"
            or confidence < current["minimum_confidence"]
        )
        if not needs_more:
            payload = result["payload"]
            validate_payload(args.task, payload)
            if args.task in {"verify-simplified", "verify-full", "repair", "adjudicate"}:
                payload["reviewer"] = f'codex-cli/{current["model"]}'
            if args.task == "recommend":
                payload["reviewer"] = f'codex-cli/{current["model"]}'
            if args.task == "grade-photo" and payload.get("error_analysis"):
                payload["error_analysis"]["image_path"] = str(images[0]) if images else None
            write_json(output_path, payload)
            analysis_output: Path | None = None
            if args.task in {"grade-text", "grade-photo", "review"} and isinstance(
                payload.get("error_analysis"), dict
            ):
                analysis_output = output_path.with_name(
                    f"{output_path.stem}.analysis.json"
                )
                write_json(analysis_output, payload["error_analysis"])
            metadata = {
                "schema": "math-codex-routing-audit/v1",
                "task": args.task,
                "result": "complete",
                "output": str(output_path.relative_to(PROJECT_ROOT)),
                "analysis_output": (
                    str(analysis_output.relative_to(PROJECT_ROOT))
                    if analysis_output else None
                ),
                "attempts": attempts,
                "database_modified": False,
            }
            audit_path = audit_route(metadata)
            return {
                "status": "ok",
                "task": args.task,
                "output": str(output_path),
                "analysis_output": str(analysis_output) if analysis_output else None,
                "audit": str(audit_path),
                "attempts": attempts,
                "database_modified": False,
            }

        if (
            args.no_auto_escalate
            or current["profile_key"] == "expert"
            or args.force_profile == "expert"
        ):
            metadata = {
                "schema": "math-codex-routing-audit/v1",
                "task": args.task,
                "result": "blocked",
                "attempts": attempts,
                "reasons": result["escalation_reasons"],
                "database_modified": False,
            }
            audit_path = audit_route(metadata)
            raise RoutingBlocked(
                f"model result requires human/clearer evidence; audit={audit_path}"
            )

        current = select_route(
            config,
            args.task,
            has_images=bool(images),
            force_profile="expert",
        )


def print_result(payload: dict[str, Any], as_json: bool) -> None:
    if as_json:
        print(json.dumps(payload, ensure_ascii=False, separators=(",", ":")))
        return
    for key, value in payload.items():
        print(f"{key}: {value}")


def build_parser(config: dict[str, Any]) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="李兆霖数学错题本 Codex CLI 模型路由器")
    sub = parser.add_subparsers(dest="command", required=True)

    install = sub.add_parser("install-profiles", help="install the three Codex CLI profiles")
    install.add_argument("--codex-home", type=Path)
    install.add_argument("--force", action="store_true")
    install.add_argument("--json", action="store_true")

    route = sub.add_parser("route", help="show the selected route without calling a model")
    route.add_argument("--task", required=True, choices=sorted(config["tasks"]))
    route.add_argument("--risk", action="append", default=[])
    route.add_argument("--has-image", action="store_true")
    route.add_argument("--force-profile", choices=sorted(config["profiles"]))
    route.add_argument("--json", action="store_true")

    run = sub.add_parser("run", help="run one bounded task through codex exec")
    run.add_argument("--task", required=True, choices=sorted(config["tasks"]))
    run.add_argument("--input")
    run.add_argument("--prompt")
    run.add_argument("--prompt-file")
    run.add_argument("--image", action="append", default=[])
    run.add_argument("--risk", action="append", default=[])
    run.add_argument("--force-profile", choices=sorted(config["profiles"]))
    run.add_argument("--out", required=True)
    run.add_argument("--timeout", type=int, default=900)
    run.add_argument("--codex-bin")
    run.add_argument("--no-auto-escalate", action="store_true")
    run.add_argument("--skip-preflight", action="store_true")
    run.add_argument("--json", action="store_true")
    return parser


def main() -> int:
    config = load_routing_config()
    parser = build_parser(config)
    args = parser.parse_args()
    try:
        if args.command == "install-profiles":
            codex_home = args.codex_home or Path(
                os.environ.get("CODEX_HOME") or Path.home() / ".codex"
            )
            payload = install_profiles(config, codex_home.resolve(), args.force)
        elif args.command == "route":
            payload = select_route(
                config,
                args.task,
                args.risk,
                has_images=args.has_image,
                force_profile=args.force_profile,
            )
            payload = {key: value for key, value in payload.items() if key != "instruction"}
        else:
            payload = run_task(args, config)
        print_result(payload, args.json)
        return 0
    except RoutingBlocked as exc:
        print_result({"status": "blocked", "error": str(exc)}, args.json)
        return 3
    except (OSError, ValueError, RuntimeError, subprocess.TimeoutExpired) as exc:
        print_result({"status": "error", "error": str(exc)}, args.json)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
